# Generated by Django 5.1.1 on 2024-10-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_up_productusermodel_up_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='publishermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu_name', models.CharField(max_length=100)),
                ('pu_address', models.CharField(max_length=100)),
                ('pu_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='bookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publishermodel')),
            ],
        ),
    ]
