# Generated by Django 5.1.1 on 2024-10-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_coursemodel_studentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizermodel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Contact_email', models.EmailField(max_length=254, unique=True)),
                ('Phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Eventmodel',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Date', models.DateTimeField()),
                ('Location', models.CharField(max_length=255)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organizermodel')),
            ],
        ),
    ]
